### ISSUE TITLE
find a test example for cvalue and cvalueH

### ISSUE THREAD

**Issue by julien-diener** [sifrproject/annotators#11]
We need to know what scores should be obtained.

**Comment by jonquet** [comment]
I am working on it. Will write it on the Google doc. 
For the moment, seems that the exemple:
http://tubo.lirmm.fr:8080/annotators/sifr_annotator?text=Les%20Plantes%20m%C3%A9dicinales%20sont%20bonnes%20a%20manger.%20Les%20Plantes%20m%C3%A9dicinales%20font%20mal%20aux%20ventres.%20Les%20plantes%20m%C3%A9dicinales%20sont%20des%20types%20de%20plantes&apikey=aa5b0e2c-5a2e-4a01-b3a2-32cf024f3f27&stop_words=est,une&ontologies=MSHFRE&max_level=1&score=old

Returns bad score for annotation with MSHFRE/D056890, it should not be 67 but 47,... something
40+exp(level1)
