### ISSUE TITLE
Implement the preprocessing of the text with TreeTager

### ISSUE THREAD

**Issue by jonquet** [sifrproject/annotators#17]
This is a sub task of https://github.com/sifrproject/ncbo_annotator/issues/4 

This consist in implementif in preprocessing of the data, before calling the annotators to normalize the input text with TreeTager when &normalize_text=true parameter is used.

**Comment by amineabdaoui** [comment]
Done.
If **lemmatize=true**, I lemmatize the input text using TreeTagger.
The annotator will display the annotations of the lemmatized input text not the original one.

**Comment by jonquet** [comment]
Note. I close this one as the feature is not finaly implemented in the proxy (annotators) but in the main ncbo_annotator code. 

See sifrproject/ncbo_annotator#4
