### ISSUE TITLE
Enable Authorization header for apikey token

### ISSUE THREAD

**Issue by jonquet** [sifrproject/annotators#20]
It seems we cannot pass the apikey parameter other than via the URL for the annotators using the proxy.

e.g., http://services.bioportal.lirmm.fr/annotator/?text=le mélanome est une mauvaise maladie&ontologies=MSHFRE&longest_only=false&exclude_numbers=false&whole_word_only=true&exclude_synonyms=false&expand_mappings=false&score=cvalue&apikey=XX
works
but without apikey in the URL it does not.

Is this simple to activate ?

**Comment by twktheainur** [comment]
It should be relatively trivial by copying the headers from one query to the next. I think that's why it doesn't work with the Authorization field at the moment
