### ISSUE TITLE
Implementation of scoring threshold within the proxy

### ISSUE THREAD

**Issue by jonquet** [sifrproject/annotators#25]
We finally decided to implement threshold filtering feature for scored annotations. 

Two annotation filtering mechanisms  will be done: 
- an absolute score threshold i.e., Annotators will only return the annotations above a certain given threshold score value
- a normalized score threshold i.e., Annotators will only return the results corresponding to a normalized value between 0 and 100 that indicates how much of the annotations to keep in proportion to the cumulative score density function. For example, a threshold of 90 will retain only the annotations with a score in the top 10% of the score distribution.

We will add 2 parameters in the API for respectively activate thee features:  
score_thrseshold
confidence_threshold (this one will take value between 0 and 100)

**Comment by jonquet** [comment]
We currently already testing this on stage.

**Comment by twktheainur** [comment]
@jonquet Please test the feature in the stageportal UI, filtering now works properly from the API and the UI
