### ISSUE TITLE
implement score old on mappings

### ISSUE THREAD

**Issue by julien-diener** [sifrproject/annotators#5]

**Comment by vemonet** [comment]
http://tubo.lirmm.fr:8080/annotators/ncbo_annotator_plus?text=Melanoma+is+a+malignant+tumor&apikey=24e03810-54e0-11e0-9d7b-005056aa3316&ontologies=MESH,SNOMEDCT&expand_mappings=true&score=old
Score for mapping should be 7 (not 8).

**Comment by vemonet** [comment]
http://tubo.lirmm.fr:8080/annotators/ncbo_annotator_plus?text=Melanoma+is+a+malignant+tumor&apikey=24e03810-54e0-11e0-9d7b-005056aa3316&ontologies=MESH,SNOMEDCT&expand_mappings=true&score=old
Some Mappings (in this case 3 of them) don't have a score
For example the mapping annotatedClass with id http://purl.bioontology.org/ontology/SNOMEDCT/20376005 has no score.

**Comment by julien-diener** [comment]
The score is not computed for mapping (this is the issue actually) but if an annotatedClass appears anywhere else, it will still get some score. Remember that the score of an annotatedClass, where ever it appears, is the sum of all scores it get throughout the whole json doc. So

  - mapping with score 8 (and not 7) only means that they got 8 "points" somewhere else
  - mapping without score means that they do not appear anywhere else (or in other mappings)

**Comment by vemonet** [comment]
Ok, for the score I was just putting what Clément said in his mail in GitHub (more convenient to track issues)

**Comment by julien-diener** [comment]
You were right, and I answered in order to be clear.

**Comment by jonquet** [comment]
Just to precise... score 8 should not occur by itself...
It is either 10+7=17 (if the other match has been done with preferred name) or 8+7=15 (if other match has been done with synonym) or something decimal (if other match was a hierachy) but not 8 itself... no ?

**Comment by julien-diener** [comment]
That's what I meant: where there is 8 currently, it should be 8+7*number-of-appearance-in-mappings. However, mappings are still not implemented. So it's only 8 for now.

**Comment by julien-diener** [comment]
To end all discussions about how it is supposed to work when the mappings are not implemented, I implemented it.

Could you guys check that this is the expected results (e.g. using the url given above by @vemonet)? So I can close this issue.
