### ISSUE TITLE
implement cvalue score

### ISSUE THREAD

**Issue by julien-diener** [sifrproject/annotators#6]

**Comment by julien-diener** [comment]
done in 230918e8b6cdafd151e9dcf2ab3b9c7e3319f2fe

**Comment by jonquet** [comment]
Ok. je vais tester ca...

**Comment by julien-diener** [comment]
1. in the link you gave, "cancer du sein" is coming up in the results.
2. but as discussed, the implementation of cvalue is not correct : annotated terms of concept B that have A in their hierarchy, should be counted in cvalue of A

**Comment by vemonet** [comment]
For the JSON link generated by the GUI : there is no error in the link
It is well generated, well encoding "\n" with "%0A"
But it seems that the Java Servlet is changing those %0A to \n before calling the annotator.

I have made a little change to the "annotators" project in the develop branch
Just adding "replace("\n", "%0A")" when building the URI used to query the annotator :
  URI uri = new URI(url.replace(" ", "%20").replace("\n", "%0A"));  

As you can see on tubo it works fine with "annotators_beta" (which is my war generated from the develop branch)
http://tubo.lirmm.fr:8080/annotators_beta/sifr_annotator?apikey=1de0a270-29c5-4dda-b043-7c3580628cd5&text=cancer%0Acancer
While it's not working on the actual one
http://tubo.lirmm.fr:8080/annotators/sifr_annotator?apikey=1de0a270-29c5-4dda-b043-7c3580628cd5&text=cancer%0Acancer

**Comment by julien-diener** [comment]
I make another issue about the "\n" problem, not to confuse

**Comment by julien-diener** [comment]
cvalue propagation to hierarchy applies also to mapping

**Comment by jonquet** [comment]
This has been finished in 2015.
