### ISSUE TITLE
API Key should not be hard coded in SIFR and IBC annotator

### ISSUE THREAD

**Issue by vemonet** [sifrproject/annotators#7]
API Key for SIFR and IBC annotator should not be hardcoded in the code
It should be provided (ideally through HTTP parameters : "Authorization") by the user

**Comment by VEmonet** [comment]
http://tubo.lirmm.fr:8080/annotators/sifr_annotator?text=cancer
Should not work

And 
http://tubo.lirmm.fr:8080/annotators/sifr_annotator?apikey=1de0a270-29c5-4dda-b043-7c3580628cd5&text=cancer
Should work

**Comment by jonquet** [comment]
Yes the idea is to transfer the parameters in order for the final service provider (either NCBO, IBC or SIFR) to know the user that identified by the service call.

**Comment by julien-diener** [comment]
done in 6067c7d4c78a744f1a40aaea1d0cc7645f0ef86d
