### ISSUE TITLE
RDF format implemented in develop branch

### ISSUE THREAD

**Issue by vemonet** [sifrproject/annotators#9]
Conversion to RDF format have been implemented in the develop branch using Soumia's class (JsonToRdf.java)
Some modifications have been done in AbstractAnnotatorServlet.java to add the functionnality and display RDF results
And the getArray() method has been added to JSON.java

Example at:
http://tubo.lirmm.fr:8080/annotators_beta/sifr_annotator?apikey=1de0a270-29c5-4dda-b043-7c3580628cd5&text=cancer&max_level=2&format=rdf

**Comment by julien-diener** [comment]
branch merged and code restructured in 0498fda5ebff7f1a59a01c084a9a1f0c23e64899

See: http://tubo.lirmm.fr:8080/annotators/sifr_annotator?apikey=1de0a270-29c5-4dda-b043-7c3580628cd5&text=cancer&max_level=2&format=rdf
